#user input variables
first_verb = input("Type a verb: ")
first_noun = input("Type a plural noun: ")
first_pronoun = input("Type a pronoun: ")
second_verb = input("Type a verb: ")
first_bodypart = input("Type a part of the body: ")
third_verb = input("Type a verb: ")
second_pronoun = input("Type a pronoun: ")
first_dayoftheweek = input("Type a day of the week: ")
second_dayoftheweek = input("Type a day of the week: ")
first_adverb = input("Type an adverb: ")
second_noun = input("Type a noun: ")
third_noun = input("Type a noun: ")
fourth_verb = input("Type a verb: ")
fourth_noun = input("Type a noun: ")
first_adjective = input("Type an adjective: ")
fifth_verb = input("Type a verb: ")
fifth_noun = input("Type a noun: ")
sixth_verb = input("Type a verb: ")
sixth_noun = input("Type a noun: ")
seventh_noun = input("Type a noun: ")
seventh_verb = input("Type a verb: ")
eighth_noun = input("Type a noun: ")
ninth_noun = input("Type a noun: ")
third_pronoun = input("Type a plural pronoun: ")
first_place = input("Type the name of a place: ")
eighth_verb = input("Type a verb: ")
tenth_noun = input("Type a plural noun: ")
eleventh_noun = input("Type a noun: ")
#Start of the Mad Lib
print("My First Mad Lib Story")
print("=================")
print("There once was a boy who liked to" + first_verb + "with")
print(first_noun)
print(".")
print("He had an a(an)" + first_pronoun + "that liked to" + second_verb)
print("his little boy" + first_bodypart)
print(". Sometimes little boy went outside")
print("to" + third_verb + "with his" + second_pronoun + "which usually")
print("happened on")
print(first_dayoftheweek + ". On" + second_dayoftheweek + "you will find the")
print("little boy" + first_adverb + "the meaning of life in the")
print(second_noun + ".")
print("inside the" + third_noun + "many things can" + fourth_verb + ".")
print("Because there is running water in the" + fourth_noun)
print("the little boy")
print("can get very" + first_adjective)
print(". Among the many things he likes")
print("to do is" + fifth_verb + "the" + fifth_noun + "and" + sixth_verb)
print(sixth_noun + ". Why the little boy does what he likes")
print("to do is unknown")
print("but one" + seventh_noun + "is for sure, the little boy knows how to")
print(seventh_verb + "a good" + eighth_noun + "in the most obscure places.")
print("Things get crazy outside of the" + ninth_noun)
print("however, another place")
print("the boy goes to have" + tenth_noun + "is the" + first_place + ".")
print("Unlike the" + first_place + "the boy can invite" + third_pronoun)
print("to the" + first_place + "and" + eighth_verb + "on the" + tenth_noun)
print("with them. Little boy who has not a name has one of the most sought")
print("after" + eleventh_noun + "s anyone could ever think of.")
